version: 1
services:
  - type: web
    name: wrf_knowledge_recommendation_app  
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py  
    runtime: python
    env: python
    region: Oregon
